---
title: "Biomass_Herbivores"
author: "Ewout Knoester"
date: "10/06/2022"
output: html_document
---

# Setup
```{r setup, include=FALSE}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks
options(scipen = 100) # Remove scientific notation

library(cowplot) # Plot grid
library(data.table) # Easy data frame handling
library(DHARMa) # glm model validation
library(emmeans) # Post hoccing
library(ggthemes) # pretty plots
library(NCmisc) # Check packages
library(panelr) # Convert data from wide to long
library(plyr) # Data summaries
library(readxl) # Import excel sheets
library(stats)
library(tidyverse) # dplyr, ggplot2, stringr
library(writexl)


```


# Data selection (preparing dataset for archiving & sharing)
```{r data selection}

# --- FISH ---
## Raw data
df0.raw <- read_excel("Raw data/Fish surveys_DATABASE_2017-2018.xlsm", sheet = 3, skip = 6, col_names = TRUE)

### Remove NA Species (= calculation cells Excel)
df1.clean <- as.data.frame(df0.raw[!is.na(df0.raw$Species),])

### Remove unused columns
df1.clean <- dplyr::select(df1.clean, -c(1, 3:11))

### Convert to long dataframe
df1.clean <- as.data.frame(long_panel(df1.clean, prefix = "_", begin = 1, end = 288, label_location = "end"))

### Sort by survey
df1.clean <- df1.clean[order(df1.clean$wave),]

# GROUPING data (functional groups)
## Load Excel
fg <- read_excel("Raw data/SpeciesList_2022-06.xlsx", sheet = 1)
fg <- dplyr::select(fg, c('Species', 'Diet', 'DietH'))

## Merge functional groups with data
df1.clean <- left_join(df1.clean, fg, by="Species")

### Remove unused columns
df1.clean <- dplyr::select(df1.clean, -c(31:35))

# META data
## Load Excel
meta <- read_excel("Raw data/Fish surveys_DATABASE_2017-2018.xlsm", sheet = 2)

# Select relevant surveys (i.e. Observer = Emilia) from RAW data using criteria of META data
meta$Comments[is.na(meta$Comments)] <- ""

# Select from df1.clean dataframe using meta dataframe criteria
df2.selex <- df1.clean[df1.clean$wave %in% c(unlist(meta[str_detect(meta$Comments, "Herbivory browsing"),1])), ]
df2.selex <- dplyr::select(df2.selex, -c('id'))
names(df2.selex)[names(df2.selex) == "wave"] <- "Survey"

# Also perform selextion on meta
meta_herbivory.browsing <- meta[str_detect(meta$Comments, "Herbivory browsing"),]

# Merge RAW and META
meta <- dplyr::select(meta, c('Survey', 'Date', 'Location')) # Relevant meta
df2.selex <- left_join(df2.selex, meta, by = "Survey") # Merge by Survey number

# EXPORT DATA SELECTION
write_xlsx(df2.selex,"Fish surveys_DATABASE_2017-2018_Herbivory grazing.xlsx")

```


```{r data loading}

df0.clean <- read_excel("Fish surveys_DATABASE_2017-2018_Herbivory grazing.xlsx", sheet = 1)

# Set factors
df0.clean$Location <- as.factor(ifelse(df0.clean$Location  == 'Firefly', 1,
                  ifelse(df0.clean$Location  == 'Pilli Pipa', 2, 
                   ifelse(df0.clean$Location  == 'Lower Mpunguti', 3, 
                    ifelse(df0.clean$Location  == 'Dolphin Point', 4, 
                     ifelse(df0.clean$Location  == 'Wasini', 6, 5))))))

df0.clean$Protection <- as.factor(ifelse(df0.clean$Location  == 1, "Fished",
                  ifelse(df0.clean$Location  == 2, "Fished", 
                   ifelse(df0.clean$Location  == 3, "Reserve", 
                    ifelse(df0.clean$Location  == 4, "Reserve", 
                     ifelse(df0.clean$Location  == 5, "No-take", "No-take"))))))
df0.clean$Protection <- factor(df0.clean$Protection, ordered = TRUE, levels = c("Fished", "Reserve", "No-take"))

df0.clean$Survey <- as.factor(df0.clean$Survey)
df0.clean$Species <- as.factor(df0.clean$Species)
df0.clean$Diet <- as.factor(df0.clean$Diet)
df0.clean$Location <- as.factor(df0.clean$Location)
df0.clean$DietH <- as.factor(df0.clean$DietH)
df0.clean$DietH <- factor(df0.clean$DietH, ordered = TRUE, levels = c("Grazers", "Browsers", "Scrapers", "Excavators", "Territorial damselfish"))
df0.clean <- as.data.frame(append(df0.clean, list(Genus = word(df0.clean$Species, 1)), after = 2))
df0.clean$Genus <- as.factor(df0.clean$Genus)

# Transform weights per survey to biomass in kg/ha
df0.clean$TOTg <- ((df0.clean$TOTg/1000)/(pi*7.5^2))*10000
names(df0.clean)[names(df0.clean) == "TOTg"] <- "Biomass.kgha"

# Subsets
df1.sizes <- dplyr::select(df0.clean, c(1:16, 32, 34, 35))

df1.bm <- dplyr::select(df0.clean, c(1, 2, 3, 16, 29, 32, 34, 35))
df1.bm <- subset(df1.bm, DietH !="Other")

# Summaries
## Herbivores per location per diet per genus
### Fish first sum per survey per genus
df2.bm.sur <- ddply(df1.bm, ~Protection+Location+Survey+DietH+Genus, summarise,
               Biomass.sur = sum(Biomass.kgha))

### Then average per location per diet per genus
df2.bm.loc <- ddply(df2.bm.sur, ~Protection+Location+DietH+Genus, summarise,
               Biomass.loc = base::mean(Biomass.sur), n = length(Biomass.sur), se = sd(Biomass.sur)/sqrt(n))

### Select Ctenochaetus (for later use)
df2.bm.loc.cte <- subset(df2.bm.loc, Genus == "Ctenochaetus")

### Remove genera that are not observed in any survey
df2.bm.loc$Genus <- droplevels(df2.bm.loc$Genus)
df2.bm.gen <- ddply(df2.bm.loc, ~Genus, summarise,
               Biomass.gen = base::mean(Biomass.loc))
df2.bm.gen$Genus <- as.character(ifelse(df2.bm.gen$Biomass.gen < 1.5, "Other", as.character(df2.bm.gen$Genus)))

df2.bm.loc <- df2.bm.loc[order(df2.bm.loc$Genus),]
df2.bm.loc <- df2.bm.loc[order(df2.bm.loc$Location),]
df2.bm.loc$Genus <- as.character(df2.bm.loc$Genus)
df2.bm.loc$Genus <- df2.bm.gen$Genus

df2.bm.loc <- ddply(df2.bm.loc, ~Protection+Location+DietH+Genus, summarise,
               Biomass.loc = base::sum(Biomass.loc)) # Sum to pool others
df2.bm.loc$Genus <- factor(df2.bm.loc$Genus, ordered = TRUE, levels = c("Acanthurus", "Centropyge", "Ctenochaetus", "Zebrasoma",
                                                             "Calotomus", "Kyphosus", "Naso", "Platax", "Siganus",
                                                             "Hipposcarus", "Scarus",
                                                             "Cetoscarus", "Chlorurus",
                                                             "Amblyglyphidodon", "Plectroglyphidodon", "Stegastes",
                                                             "Other"))

## Herbivores per location (per functional group)
### Fish first sum per survey
df2.bm.sur.fg <- ddply(df1.bm, ~Protection+Location+DietH+Survey, summarise,
               Biomass.herb = sum(Biomass.kgha))

### Then average per location
df2.bm.loc.fg <- ddply(df2.bm.sur.fg, ~Protection+Location+DietH, summarise,
               Biomass.loc.fg = base::mean(Biomass.herb), n = length(Biomass.herb), se = sd(Biomass.herb)/sqrt(n))

### Subset grazers only
df2.bm.loc.fg <- subset(df2.bm.loc.fg, DietH == "Grazers")

## Herbivores per location (all herbivores summed)
### Fish first sum per survey
df2.bm.sur.herb <- ddply(df1.bm, ~Protection+Location+Survey, summarise,
               Biomass.herb = sum(Biomass.kgha))

### Then average per location
df2.bm.loc.herb <- ddply(df2.bm.sur.herb, ~Protection+Location, summarise,
               Biomass.loc.herb = base::mean(Biomass.herb), n = length(Biomass.herb), se = sd(Biomass.herb)/sqrt(n))

```

# Data exploration
```{r explore}

hist(df2.bm.sur.herb$Biomass.herb)
hist(sqrt(df2.bm.sur.herb$Biomass.herb))
hist(log(df2.bm.sur.herb$Biomass.herb))
hist(log10(df2.bm.sur.herb$Biomass.herb))

```


# Model selection
```{r SGR: linear model selection}


# Prepare data
model.data <- df2.bm.sur.herb

# Set zero to minimum value
model.data$Biomass.herb[model.data$Biomass.herb == 0] <- min(model.data$Biomass.herb[model.data$Biomass.herb>0])/2

# Model
glm.1 <- glm(formula = Biomass.herb ~ Location, family  = Gamma(link = "log"), data = model.data)

car::Anova(glm.1)

```

## Model validation
```{r SGR model validation}

mod <- glm.1
modOutput <- simulateResiduals(fittedModel = mod, plot = F)

op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2))
plotResiduals(modOutput, quantreg = T, quantiles = 0.5, rank = T, smoothScatter = F)
testDispersion(modOutput)
testUniformity(modOutput)
plotResiduals(modOutput, form = model.data$Location)
abline(0,0)
base::plot(fitted(mod) ~ model.data$Biomass.herb)
par(op)


```


# Post hoc
```{r post hoc}
hsd <- emmeans(glm.1, specs = pairwise ~ Location, adjust = "tukey")
```

```{r}
# Stacked bar graph + SE

# Post hoc letters
sigletters.loc <- multcomp::cld(hsd$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Make order match with summary dataframe
sigletters.loc <- sigletters.loc[order(sigletters.loc$Location),]
sigletters.loc <- sigletters.loc %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
df2.bm.loc.herb <- cbind(df2.bm.loc.herb, siglet.loc = sigletters.loc$.group)

df2.bm.loc.SE <- cbind(df2.bm.loc, se.loc = df2.bm.loc.herb$se)
df2.bm.loc.SE <- cbind(df2.bm.loc.SE, sum.tot = df2.bm.loc.herb$Biomass.loc.herb)
df2.bm.loc.SE <- cbind(df2.bm.loc.SE, siglet = df2.bm.loc.herb$siglet.loc)

df2.bm.loc.SE$se.loc <- as.numeric(ifelse(df2.bm.loc.SE$DietH  == 'Browsers' & df2.bm.loc.SE$Genus == "Naso", df2.bm.loc.SE$se.loc, ""))
df2.bm.loc.SE$sum.tot <- as.numeric(ifelse(df2.bm.loc.SE$DietH  == 'Browsers' & df2.bm.loc.SE$Genus == "Naso", df2.bm.loc.SE$sum.tot, ""))
df2.bm.loc.SE$siglet <- ifelse(df2.bm.loc.SE$DietH  == 'Browsers' & df2.bm.loc.SE$Genus == "Naso", df2.bm.loc.SE$siglet, "")

gencol <- c("#5637A4", "#4026FF", "#4FD2FF", # Grazers
            "#268451", "#32AB50", "#A1DF56", "#E3F5B5", # Browsers
            "#C84D45", "#F99286", # Scrapers
            "#9D489D", # Excavators
            "#FFFD7A", "#C9AB56", # Territorial damselfish
            "#E5E5E5") # Other

p1SE <- ggplot(df2.bm.loc.SE) +  
  geom_bar(position = "stack", stat = "identity", aes(x = Location, y = Biomass.loc, fill=Genus))+
  geom_errorbar(data=df2.bm.loc.herb, aes(x=Location, ymin=Biomass.loc.herb, ymax=Biomass.loc.herb+(1*se)),
                width=.2, size=1, position=position_dodge(.9))+
  geom_text(data=df2.bm.loc.herb, aes(x=Location, y=Biomass.loc.herb+(1*se), label=siglet.loc), 
            vjust=-0.8, hjust=0.5, size=5, fontface="bold", position=position_dodge(.9))+
  geom_bar(data=df2.bm.loc.herb, stat="identity", aes(x=Location, y=Biomass.loc.herb), alpha=0, size=1, color="black")+
  scale_fill_manual("Genus" , values = gencol)+
  facet_wrap(~Protection, scales="free_x")+
  theme_economist()+ scale_colour_economist()+
  labs(x="Study site", y=expression(paste("Biomass (kg ", ha^-1,")")))+
  scale_x_discrete(expand=c(0, 0.7))+
  scale_y_continuous(expand=c(0, 0), limits=c(0, 599))+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size=14, face="bold", vjust=2, margin=margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    legend.position = "right",
    legend.title = element_text(size = 12, face = "bold", hjust = 0.3),
    legend.text = element_text(size = 11.5, face = "italic"),
    legend.key.size = unit(1.1, "lines"),
    axis.title.x = element_text(size=14, vjust=-2),
    axis.text.x = element_text(size=12, face="bold", vjust=0.5),
    axis.title.y = element_text(size=14, vjust=4),
    axis.text.y = element_text(size=12, face="bold", vjust=0.4),
    panel.background = element_rect(fill="#FCFCFC"),
    plot.background = element_rect(fill="#FFFFFF"),
    panel.grid.major = element_line(colour = "#FFFFFF", size=1),
    axis.ticks = element_blank(),
    legend.margin = unit(c(10,0,10,0), "cm"))
    
# Create dataframe for legend    
dt <- data.table(x=1, y=seq(1, 13, 1), z=factor(1:13))
dt[, grp:= cut(as.numeric(z), breaks=c(0, 1, 3, 4, 6, 9, 13),
                labels=c("", "Damselfish", "Excavators", "Scrapers", "Browsers", "Grazers"))]
dt2 <- dt[, .(x=1, y=min(y), yend=max(y), ymid=base::mean(y)), by=grp]
dt3 <- data.table(x=1, y=unlist(dt2[ , .(y, yend)]))
v <- 0.3 # offset

p2 <- ggplot(mapping = aes(x=x, y=y)) +
  geom_point(data=dt, size=5)+
  geom_segment(data=dt2, aes(x=x+v, xend=x+v, yend=yend),
               colour=c("#FFFFFF", "#dfd20b", "#803280", "#991d1f", "#11813f", "#3853a4"), size=1)+
  geom_segment(data=dt3, aes(x=x+v, xend=x+(v-0.1), yend=y), size=1, 
    colour=c("#FFFFFF", # NA (Other floor)
             "#dfd20b", # Damsel floor
             "#803280", # Excavator floor
             "#991d1f", # Scraper floor
             "#11813f", # Browser floor 
             "#3853a4", # Grazer floor
             "#FFFFFF", # Other (ceiling)
             "#dfd20b", # Damsel ceiling
             "#803280", # Excavator ceiling
             "#991d1f", # Scraper ceiling
             "#11813f", # Browser ceiling 
             "#3853a4"))+ # Grazer ceiling
  geom_text(data=dt2, aes(x=x+v+0.4, y=ymid, label=grp),
    colour=c("#959595", "#dfd20b", "#803280", "#991d1f", "#11813f", "#3853a4"), size=4, fontface="bold", vjust=0.3)+
  scale_color_manual(values="", guide="none")+
  scale_x_continuous(limits = c(1.2, 2))+
  theme_void()+
  theme(plot.margin = unit(c(0.3,0,0.1,0), "cm"))


plot_grid(p1SE, plot_grid(NULL, p2, NULL, nrow = 3, rel_heights = c(1, 5, 1)), rel_widths = c(6, 1))

ggsave("Herbivores by genus and diet_SE.tiff", width = 23, height = 11, units = "cm", dpi=1200, compression = "lzw")



```

# Save summary data to Excel for correlations
```{r corexcel}

Herbivores <- dplyr::select(df2.bm.loc.herb, c('Location', 'Biomass.loc.herb', 'se'))
names(Herbivores)[names(Herbivores) == "se"] <- "Biomass.loc.herb.se"
Herbivores$Biomass.loc.grazers <- df2.bm.loc.fg$Biomass.loc.fg
Herbivores$Biomass.loc.grazers.se <- df2.bm.loc.fg$se
Herbivores$Biomass.loc.cte <- df2.bm.loc.cte$Biomass.loc
Herbivores$Biomass.loc.cte.se <- df2.bm.loc.cte$se

write_xlsx(Herbivores,"Correlation data/Correlations_Herbivores.xlsx")

# Grazers as percentage of total herbivores
Grazers <- select(Herbivores, c('Location', 'Biomass.loc.herb', 'Biomass.loc.grazers'))
Grazers$Percentage <- (Grazers$Biomass.loc.grazers/Grazers$Biomass.loc.herb)*100

```

# Check packages used
```{r}

knitr::purl("Biomass_Herbivores.Rmd")
list.functions.in.file("Biomass_Herbivores.R")
unlink("Biomass_Herbivores.R")

```









