
---
title: "Grazing_Fouling"
author: "Ewout Knoester"
date: "17/01/2022"
output: html_document
---

# Set R and packages
```{r setup}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks

library(car) # ANOVA results GLM
library(data.table) # Easy data frame handling
library(emmeans) # Post hoccing
library(flextable) # Layout table
library(ggthemes) # Pretty plots
library(NCmisc) # Check packages used
library(nlme) # GLS
library(officer) # Move table into word
library(rstatix) # graphics (?)
library(tidyverse) # ggplot, dplyr, tidyr, stringr, tibble
library(writexl)

# Function to facilitate averaging dataset
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(sum = sum(x[[col]]),
      mean = base::mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]])))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- plyr::rename(data_sum, c("mean" = varname))
 return(data_sum)
}

```

# Load and organize
```{r prepare data}

# Load data (data from herbivory grazing experiment only)
df0.raw <- read.csv("Fouling_Herbivory grazing_2022-01.csv", header=T, na.strings=c(""))

# Select relevant columns
df1.clean <- dplyr::select(df0.raw, c('Location', 'Structure', 'Fouling', 'Difference.g'))

# Rename
names(df1.clean)[names(df1.clean) == "Difference.g"] <- "Weight"

#! Standardize weight per unit of surface area (PPR pipes of a nursery structure has surface area of 0.16m2)
df1.clean$Weight <- df1.clean$Weight/0.16 # Weight now in g/m2

# Change location names to numbers
df1.clean$Location <- as.factor(ifelse(df1.clean$Location  == 'Firefly', 1,
                  ifelse(df1.clean$Location  == 'Pilli Pipa', 2, 
                   ifelse(df1.clean$Location  == 'Lower Mpunguti', 3, 
                    ifelse(df1.clean$Location  == 'Dolphin Point', 4, 
                     ifelse(df1.clean$Location  == 'Kisite', 5, 6))))))

# Set Protection per Location
df1.clean$Protection <- as.factor(ifelse(df1.clean$Location  == 1, "Fished",
                  ifelse(df1.clean$Location  == 2, "Fished", 
                   ifelse(df1.clean$Location  == 3, "Reserve", 
                    ifelse(df1.clean$Location  == 4, "Reserve", 
                     ifelse(df1.clean$Location  == 5, "No-take", "No-take"))))))
df1.clean$Protection <- factor(df1.clean$Protection, ordered = TRUE, levels = c("Fished", "Reserve", "No-take"))

# Set data types right
df1.clean$Fouling <- factor(df1.clean$Fouling)
df1.clean$Structure <- factor(df1.clean$Structure)

# Pool some fouling groups and set order
levels(df1.clean$Fouling) <- c("Shelled animals", "Macroalgae", "CCA", "Turf algae", "Macroalgae", "Shelled animals", "Other", "Other", "Other", "Other", "Turf algae")
df1.clean$Fouling <- factor(df1.clean$Fouling, levels = c("Turf algae", "Macroalgae", "CCA", "Shelled animals", "Other"))

# Select summed data to get proper averages across pooled groups
df1.clean <- data_summary(df1.clean, varname = "Weight", groupnames = c("Protection", "Location", "Structure", "Fouling"))
df1.clean <- dplyr::select(df1.clean, c('Protection':'sum'))
names(df1.clean)[names(df1.clean) == "sum"] <- "Weight"

# Get summary per Fouling group
df1.clean.sum <- data_summary(df1.clean, varname = "Weight", groupnames = c("Protection", "Location", "Fouling"))

# Get summary of total Fouling
df1.clean.tot.temp <- data_summary(df1.clean, varname = "Weight", groupnames = c("Protection", "Location", "Structure"))
df1.clean.tot.temp <- dplyr::select(df1.clean.tot.temp, c('Protection':'sum')) # Get sum of all fouling groups
names(df1.clean.tot.temp)[names(df1.clean.tot.temp) == "sum"] <- "Weight.tot"

# Get the average total fouling of each study site for the 8 replicate structures
df1.clean.tot.sum <- data_summary(df1.clean.tot.temp, varname = "Weight.tot", groupnames = c("Protection", "Location"))
df1.clean.tot.sum <- dplyr::select(df1.clean.tot.sum, -c('sum')) # Remove the sum

# Same for transformed data
df1.clean.tot.temp$Weight.log <- log10(df1.clean.tot.temp$Weight.tot)
df1.clean.tot.sum.log <- data_summary(df1.clean.tot.temp, varname = "Weight.log", groupnames = c("Protection", "Location"))

# Prepare data for MANOVA
df1.clean <- tibble::rownames_to_column(df1.clean, "ID")
df1.clean$ID <- paste(df1.clean$Location, ".", df1.clean$Structure)
df2.wide <- dcast(setDT(df1.clean), 
      ID ~ rowid(ID, prefix = "Foulings"),
      value.var = "Weight")
df2.wide <- separate(data = df2.wide, col = ID, into = c("Location", "Structure"), sep = " . ")
names(df2.wide) <- c("Location", "Structure", "Turf.algae", "Macroalgae", "CCA", "Shelled.animals", "Other")

df2.wide$Location <- factor(df2.wide$Location)
df2.wide$Structure <- factor(df2.wide$Structure)
df2.wide <- tibble::rownames_to_column(df2.wide, "ID")
df2.wide <- as.data.frame(df2.wide)

# Set Protection per Location
df2.wide$Protection <- as.factor(ifelse(df2.wide$Location  == 1, "Fished",
                  ifelse(df2.wide$Location  == 2, "Fished", 
                   ifelse(df2.wide$Location  == 3, "Reserve", 
                    ifelse(df2.wide$Location  == 4, "Reserve", 
                     ifelse(df2.wide$Location  == 5, "No-take", "No-take"))))))
df2.wide$Protection <- factor(df2.wide$Protection, ordered = TRUE, levels = c("Fished", "Reserve", "No-take"))

# Get summaries per group
df2.wide.TA <- data_summary(df2.wide, varname = c("Turf.algae"), groupnames = c("Protection", "Location"))
df2.wide.MA <- data_summary(df2.wide, varname = c("Macroalgae"), groupnames = c("Protection", "Location"))
df2.wide.CCA <- data_summary(df2.wide, varname = c("CCA"), groupnames = c("Protection", "Location"))
df2.wide.SA <- data_summary(df2.wide, varname = c("Shelled.animals"), groupnames = c("Protection", "Location"))

# LOG10 transformations
df2.wide.log <- df2.wide
df2.wide.log$Turf.algae <- log10(df2.wide$Turf.algae+0.05)
df2.wide.log$Macroalgae <- log10(df2.wide$Macroalgae+0.05) 
df2.wide.log$CCA <- log10(df2.wide$CCA+0.05) 
df2.wide.log$Shelled.animals <- log10(df2.wide$Shelled.animals+0.05) 
df2.wide.log$Other <- log10(df2.wide$Other+0.05)

```

# Data exploration
```{r data exploration}

hist(df1.clean.tot.temp$Weight.tot) # Log10 likely needed for linear regression (total weight)

```

# Model selection
```{r SGR: linear model selection}

# TOTAL FOULING
## Weight totaled over all fouling groups
gls1  <- gls(Weight.tot ~ Location, data = df1.clean.tot.temp)

## Allowing for heterogeneity among Locations improves residuals
gls1.w  <- gls(Weight.tot ~ Location, weights = varIdent(form = ~ 1|Location), data = df1.clean.tot.temp)

## Log10 of response variable improves residuals
gls1.w.log  <- gls(log10(Weight.tot) ~ Location, weights = varIdent(form = ~ 1|Location), data = df1.clean.tot.temp)

## Output
car::Anova(gls1.w.log)
base::summary(gls1.w.log)

# FOULING PER GROUP
## Couldn't fulfill assumptions for MANOVA, so try separate GLS instead
## Fouling group 'Other' excluded because to few observations

## Models
TA <- gls(Turf.algae ~ Location, weights=varIdent(form = ~ 1 | Location), data = df2.wide.log)
MA <- gls(Macroalgae ~ Location, weights=varIdent(form = ~ 1 | Location), data = df2.wide.log)
CCA <- gls(CCA ~ Location, weights=varIdent(form = ~ 1 | Location), data = df2.wide.log)
SA <- gls(Shelled.animals ~ Location, weights=varIdent(form = ~ 1 | Location), data = df2.wide.log)

## Outputs
car::Anova(TA)
car::Anova(MA)
car::Anova(CCA)
car::Anova(SA)


```

# Model validation
```{r model validation}

# TOTAL FOULING
mod <- gls1.w.log # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
base::plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(df1.clean.tot.temp$Location, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
base::plot(df1.clean.tot.temp$Protection, resid(mod, type = "pearson")) # residuals split over Treatment
abline(0,0)
base::plot(fitted(mod) ~ log10(df1.clean.tot.temp$Weight.tot)) # response data vs fitted
par(op)

# FOULING PER GROUP
## Turf.algae
mod <- TA # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
base::plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
base::plot(df2.wide.log$Location, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
base::plot(fitted(mod) ~ log10(df2.wide.log$Turf.algae+0.05)) # response data vs fitted
par(op)

## Macroalgae
mod <- MA # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
base::plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
base::plot(df2.wide.log$Location, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
base::plot(fitted(mod) ~ log10(df2.wide.log$Macroalgae+0.05)) # response data vs fitted
par(op)

## CCA
mod <- CCA # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
base::plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
base::plot(df2.wide.log$Location, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
base::plot(fitted(mod) ~ log10(df2.wide.log$CCA+0.05)) # response data vs fitted
par(op)

## Shelled.animals
mod <- TA # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
base::plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
base::plot(df2.wide.log$Location, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
base::plot(fitted(mod) ~ log10(df2.wide.log$Shelled.animals+0.05)) # response data vs fitted
par(op)

```
# Post hoc
```{r post hoc}

# TOTAL FOULING
hsd <- emmeans(gls1.w.log, specs = pairwise ~ Location, adjust = "tukey", type = "response")

# FOULING PER GROUP
hsd.TA <- emmeans(TA, specs = pairwise ~ Location, adjust = "tukey", type = "response")
hsd.MA <- emmeans(MA, specs = pairwise ~ Location, adjust = "tukey", type = "response")
hsd.CCA <- emmeans(CCA, specs = pairwise ~ Location, adjust = "tukey", type = "response")
hsd.SA <- emmeans(SA, specs = pairwise ~ Location, adjust = "tukey", type = "response")

```

# Unused plots
```{r unused plots}

# Location only
# Post hoc letters
sigletters.loc <- multcomp::cld(hsd$emmeans, alpha = 0.05, Letters = letters, reversed = TRUE) # get CLD

# Make order match with summary dataframe
sigletters.loc <- sigletters.loc[order(sigletters.loc$Location),]
sigletters.loc <- sigletters.loc %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
df3.summary.Loc <- cbind(df1.clean.tot.sum, siglet.loc = sigletters.loc$.group)

# Plot
ggplot(df3.summary.Loc, aes(x = Location, y = Weight.tot))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  facet_wrap(~ Protection, scales="free_x")+
  labs(y = expression(paste("Fouling (g ", m^-2,")")))+
  scale_y_continuous(limits = c (0, 400), expand = c(0,0))+
  geom_errorbar(aes(ymin=Weight.tot-(1*se), ymax=Weight.tot+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = df3.summary.Loc, aes(x=Location, y = Weight.tot + (1*se), label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_x_discrete(expand = c(0, 0.7))+
  theme_economist()+scale_colour_economist()+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size = 14, face = "bold", vjust = 2, margin = margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    axis.title.x = element_text(color="black", vjust=-2, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=4, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3),
    axis.ticks = element_blank()
    )

# Plot Location | Fouling
# Stacked bar graph
ggplot(df1.clean.sum, aes(x = Location, y = Weight, fill = Fouling)) + 
  geom_bar(position = "stack", stat="identity", colour = "black") +
  scale_fill_manual("Fouling", values = c("#93ED8A", "#0C8900", "#FFCAFB", "#BFBFBF", "#363636"))+
  facet_wrap(~ Protection, scales="free_x")+
  theme_economist()+scale_colour_economist()+
  labs(y = expression(paste("Fouling (g ", m^-2,")")))+
  #geom_segment(data = dt2, aes(x = 1, xend = 2, yend = -1), colour = "black", size = 2)+
  scale_x_discrete(expand = c(0, 0.7))+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 300))+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size = 14, face = "bold", vjust = 2, margin = margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    legend.position = "right",
    legend.title = element_text(size = 12, face = "bold", hjust = 0.3),
    legend.text = element_text(size = 11, face = "italic"),
    axis.title.x = element_text(size = 14, vjust = -2),
    axis.text.x = element_text(size = 12, face = "bold", vjust = 0.5),
    axis.title.y = element_text( size = 14, vjust = 4),
    axis.text.y = element_text(size = 12, face = "bold", vjust = 0.4),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#FFFFFF", size = 1),
    axis.ticks = element_blank()
    ) 

# Turf.algae
# Post hoc letters
sigletters.TA <- multcomp::cld(hsd.TA$emmeans, alpha = 0.05, Letters = letters, reversed = TRUE) # get CLD

# Make order match with summary dataframe
sigletters.TA <- sigletters.TA[order(sigletters.TA$Location),]
sigletters.TA <- sigletters.TA %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
df3.summary.TA <- cbind(df2.wide.TA, siglet.loc = sigletters.TA$.group)

# Plot
ggplot(df3.summary.TA, aes(x = Location, y = Turf.algae))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  facet_wrap(~ Protection, scales="free_x")+
  labs(y = expression(paste("Turf algae (g ", m^-2,")")))+
  scale_y_continuous(limits = c(0, 80), expand = c(0,0))+
  geom_errorbar(aes(ymin=Turf.algae-(1*se), ymax=Turf.algae+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = df3.summary.TA, aes(x=Location, y = Turf.algae + (1*se), label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_x_discrete(expand = c(0, 0.7))+
  theme_economist()+scale_colour_economist()+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size = 14, face = "bold", vjust = 2, margin = margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    axis.title.x = element_text(color="black", vjust=-2, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=4, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3),
    axis.ticks = element_blank()
    )

# Macroalgae
# Post hoc letters
sigletters.MA <- multcomp::cld(hsd.MA$emmeans, alpha = 0.05, Letters = letters, reversed = TRUE) # get CLD

# Make order match with summary dataframe
sigletters.MA <- sigletters.MA[order(sigletters.MA$Location),]
sigletters.MA <- sigletters.MA %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
df3.summary.MA <- cbind(df2.wide.MA, siglet.loc = sigletters.MA$.group)

# Plot
ggplot(df3.summary.MA, aes(x = Location, y = Macroalgae))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  facet_wrap(~ Protection, scales="free_x")+
  labs(y = expression(paste("Macroalgae (g ", m^-2,")")))+
  scale_y_continuous(limits = c(0, 180), expand = c(0,0))+
  geom_errorbar(aes(ymin=Macroalgae-(1*se), ymax=Macroalgae+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = df3.summary.MA, aes(x=Location, y = Macroalgae + (1*se), label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_x_discrete(expand = c(0, 0.7))+
  theme_economist()+scale_colour_economist()+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size = 14, face = "bold", vjust = 2, margin = margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    axis.title.x = element_text(color="black", vjust=-2, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=4, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3),
    axis.ticks = element_blank()
    )

# CCA
# Post hoc letters
sigletters.CCA <- multcomp::cld(hsd.CCA$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE) # get CLD

# Make order match with summary dataframe
sigletters.CCA <- sigletters.CCA[order(sigletters.CCA$Location),]
sigletters.CCA <- sigletters.CCA %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
df3.summary.CCA <- cbind(df2.wide.CCA, siglet.loc = sigletters.CCA$.group)

# Plot
ggplot(df3.summary.CCA, aes(x = Location, y = CCA))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  facet_wrap(~ Protection, scales="free_x")+
  labs(y = expression(paste("CCA (g ", m^-2,")")))+
  scale_y_continuous(limits = c(0, 75), expand = c(0,0))+
  geom_errorbar(aes(ymin=CCA-(1*se), ymax=CCA+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = df3.summary.CCA, aes(x=Location, y = CCA + (1*se), label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_x_discrete(expand = c(0, 0.7))+
  theme_economist()+scale_colour_economist()+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size = 14, face = "bold", vjust = 2, margin = margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    axis.title.x = element_text(color="black", vjust=-2, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=4, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3),
    axis.ticks = element_blank()
    )

# Shelled.animals
# Post hoc letters
sigletters.SA <- multcomp::cld(hsd.SA$emmeans, alpha = 0.05, Letters = letters, reversed = TRUE) # get CLD

# Make order match with summary dataframe
sigletters.SA <- sigletters.SA[order(sigletters.SA$Location),]
sigletters.SA <- sigletters.SA %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
df3.summary.SA <- cbind(df2.wide.SA, siglet.loc = sigletters.SA$.group)

# Plot
ggplot(df3.summary.SA, aes(x = Location, y = Shelled.animals))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  facet_wrap(~ Protection, scales="free_x")+
  labs(y = expression(paste("Shelled animals (g ", m^-2,")")))+
  scale_y_continuous(limits = c(0, 160), expand = c(0,0))+
  geom_errorbar(aes(ymin=Shelled.animals-(1*se), ymax=Shelled.animals+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = df3.summary.SA, aes(x=Location, y = Shelled.animals + (1*se), label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_x_discrete(expand = c(0, 0.7))+
  theme_economist()+scale_colour_economist()+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size = 14, face = "bold", vjust = 2, margin = margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    axis.title.x = element_text(color="black", vjust=-2, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=4, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3),
    axis.ticks = element_blank()
    )

```


# TOTAL Plots
```{r total plots}

# Stacked bar graph + errors

# Merge datas
df1.clean.sum <- df1.clean.sum[order(df1.clean.sum$Location),]
df1.clean.sum <- df1.clean.sum[order(df1.clean.sum$Fouling),]
df1.clean.sum.se <- cbind(df1.clean.sum, se.tot = df3.summary.Loc$se)
df1.clean.sum.se <- cbind(df1.clean.sum.se, Weight.tot = df3.summary.Loc$Weight.tot)
df1.clean.sum.se <- cbind(df1.clean.sum.se, siglet = df3.summary.Loc$siglet.loc)
df1.clean.sum.se$se.tot <- as.numeric(ifelse(df1.clean.sum.se$Fouling  != 'CCA', "", df1.clean.sum.se$se.tot))
df1.clean.sum.se$Weight.tot <- as.numeric(ifelse(df1.clean.sum.se$Fouling  != 'CCA', "", df1.clean.sum.se$Weight.tot))
df1.clean.sum.se$siglet <- ifelse(df1.clean.sum.se$Fouling  != 'CCA', "", df1.clean.sum.se$siglet)

# Plot
ggplot(df1.clean.sum.se) +  
  geom_bar(position = "stack", stat = "identity", aes(x = Location, y = Weight, fill=Fouling))+
  geom_errorbar(aes(x = Location, ymin=Weight.tot, ymax=Weight.tot+(1*se.tot)), width=.2, size = 1, position=position_dodge(.9))+
  geom_text(data = df1.clean.sum.se, aes(x=Location, y = Weight.tot + (1*se.tot), label = siglet), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  geom_bar(data=df1.clean.sum.se[(df1.clean.sum.se$Fouling=="CCA"),], show.legend = FALSE,
           stat = "identity", aes(x = Location, y = Weight.tot, fill=Fouling), alpha=0, size=1, color="black")+
  scale_fill_manual("Fouling", values = c("#93ED8A", "#0d9600", "#FFCAFB", "#969696", "#2e2e2e"))+
  facet_wrap(~ Protection, scales="free_x")+
  theme_economist()+scale_colour_economist()+
  labs(x = "Study site", y = expression(paste("Fouling (g ", m^-2,")")))+
  #geom_segment(data = dt2, aes(x = 1, xend = 2, yend = -1), colour = "black", size = 2)+
  scale_x_discrete(expand = c(0, 0.7))+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 400))+
  theme(
    panel.margin.y = unit(0, "cm"),
    strip.text.x = element_text(size = 14, face = "bold", vjust = 2, margin = margin(0.2, 0, 0.1, 0, "cm")),
    strip.background = element_blank(),
    legend.position = "right",
    legend.title = element_text(size = 12, face = "bold", hjust = 0.3),
    legend.text = element_text(size = 12),
    axis.title.x = element_text(size = 14, vjust = -2),
    axis.text.x = element_text(size = 12, face = "bold", vjust = 0.5),
    axis.title.y = element_text( size = 14, vjust = 4),
    axis.text.y = element_text(size = 12, face = "bold", vjust = 0.4),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#FFFFFF", size = 1),
    axis.ticks = element_blank()
    ) 
ggsave("Fouling_Stacked_Location_SE.tiff", width = 23, height = 11, units = "cm", dpi=1200, compression = "lzw")

```

# Table per fouling type
```{r table}

Tab <- dplyr::select(df1.clean.sum, c('Fouling', 'Location', 'Weight', 'se'))
Tab <- subset(Tab, Fouling != "Other")
Siglets <- c(df3.summary.TA$siglet.loc, df3.summary.MA$siglet.loc, df3.summary.CCA$siglet.loc, df3.summary.SA$siglet.loc)
Tab$Siglets <- Siglets
Tab$Weight <- round(Tab$Weight, 1)
Tab$se <- round(Tab$se, 1)
names(Tab) <- c("Type of fouling", "Location", "Weight (g/m2)", "Standard error", "CLD")

# create new word document
new.word.doc=function(){
  my.doc=read_docx()
  return(my.doc)
}

# add an empty line
add.empty.line=function(doc){
  body_add_par(doc, " ")
  return("empty line added")
}

# add a data frame as a table
add.table=function(doc, tbl, col.keys=NULL, col.digits=NULL){
  # create basic flextable
  f.table=qflextable(tbl)
  
  # set table borders
  f.table=border_inner_h(f.table, part="header", border=fp_border(color="black", width = 1))
  #f.table=border_inner_v(f.table, part="all", border=fp_border(color="black", width = 1))
  
  # set fonts
  f.table=flextable::font(f.table,  fontname = "Times", part = "all")
  # also set the table's header font as bold
  f.table=bold(f.table, part = "header")
  
  # add the table to the document
  flextable::body_add_flextable(doc, 
                                value = f.table, 
                                align = "left" )
  return("table added")
}

# create a new document object
doc=new.word.doc()
add.empty.line(doc)
add.table(doc, Tab)

# generate the Word document using the print function
base::print(doc, target="Fouling post hoc per type.docx")

```
# Save summary data to Excel for correlations
```{r corexcel}

Fouling <- dplyr::select(df1.clean.tot.sum, c('Location', 'Weight.tot', 'se'))
names(Fouling)[names(Fouling) == "se"] <- "Weight.tot.se"
Fouling$Weight.log <- df1.clean.tot.sum.log$Weight.log
Fouling$Weight.log.se <- df1.clean.tot.sum.log$se

write_xlsx(Fouling,"Correlation data/Correlations_Fouling.xlsx")

```

# Check packages used
```{r}

knitr::purl("Grazing_Fouling.Rmd")
list.functions.in.file("Grazing_Fouling.R")
unlink("Grazing_Fouling.R")

```







